print('WVC Contruções')
print('-=' * 30)
cidade = str(input('Cidade: '))
bairro = str(input('Bairro: '))
tipo = str(input('Tipo de terreno: '))
print('Dimenções do terreno')
largura = int(input('Largura: '))
comprimento = int(input('Comprimento: '))
Aquisição = float(input('Data de aquisição: '))
print('-=' * 30)