print('WVC Contruções')
print('-=' * 30)
cidade = str(input('Cidade: ')).strip().upper()
bairro = str(input('Bairro: ')).strip().upper()
tipo = str(input('Tipo de terreno: ')).strip().upper()
print('Dimenções do terreno')
largura = int(input('Largura: '))
comprimento = int(input('Comprimento: '))
Aquisição = float(input('Data de aquisição: '))
print('-=' * 30)
