frase = '   Curso em Video Python  '
print(len(frase.split()))
print(frase.count('o',0,20))
print(frase.find('Android'))
print('Curso'in frase)
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.strip())
print('-'.join(frase))
