n = input('Digite alguma coisa: ')
print('voce digitou:',n)
print(n,'É',type(n))
print('É alfanumerico:',n.isalnum())
print('É alfabetico:',n.isalpha())
print(n.isascii())
print(n.isdecimal())
print(n.isidentifier())
print(n.isdigit())
print('Esta Tudo em minusculo:',n.islower())
print('É possivel converter esse valor em um numero:',n.isnumeric())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print('Esta tudo em maiusculo:',n.isupper())
